"""add headers.hash_from_link

Revision ID: 167935963b67
Revises: 3bdfd5a33f8c
Create Date: 2020-05-29 12:32:58.006184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167935963b67'
down_revision = '3bdfd5a33f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headers', sa.Column('hash_from_link', sa.BigInteger(), nullable=False))
    op.create_unique_constraint('headers_ukey', 'headers', ['hash_from_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('headers_ukey', 'headers', type_='unique')
    op.drop_column('headers', 'hash_from_link')
    # ### end Alembic commands ###
