"""alter articles

Revision ID: 3bdfd5a33f8c
Revises: 507ca94fb4f3
Create Date: 2020-05-28 17:43:25.292555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdfd5a33f8c'
down_revision = '507ca94fb4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('articles_ukey', 'articles', ['headers_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_ukey', 'articles', type_='unique')
    # ### end Alembic commands ###
